export interface Course {
  id: string; icon: string; title: string; cat: 'Medical' | 'Premed';
  color: string; free: boolean; desc: string;
  image: string; staticImages: string[]; topics: string[];
}

export const COURSES: Course[] = [
  { id:'anatomy', icon:'🫀', title:'Human Anatomy', cat:'Medical', color:'#f76f6f', free:true,
    desc:'Comprehensive study of body structures from gross anatomy to microanatomy.',
    image:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Gray1124.png/400px-Gray1124.png',
    staticImages:['https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Diagram_of_the_human_heart_%28cropped%29.svg/300px-Diagram_of_the_human_heart_%28cropped%29.svg.png','https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Cerebrum_lobes.svg/300px-Cerebrum_lobes.svg.png'],
    topics:['Musculoskeletal System','Cardiovascular Anatomy','Neuroanatomy','Thorax & Abdomen','Head & Neck','Upper & Lower Limbs','Reproductive Anatomy','Lymphatic System'] },
  { id:'physio', icon:'⚡', title:'Physiology', cat:'Medical', color:'#4f8ef7', free:true,
    desc:'How the body functions at cellular, organ, and system levels.',
    image:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Skeletal_muscle.jpg/400px-Skeletal_muscle.jpg',
    staticImages:['https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Kidney_nephron_molar_transport_diagram.svg/300px-Kidney_nephron_molar_transport_diagram.svg.png'],
    topics:['Cell Physiology','Cardiac Physiology','Respiratory Physiology','Renal Physiology','Endocrine Physiology','Neurophysiology','GI Physiology','Reproductive Physiology'] },
  { id:'biochem', icon:'🧬', title:'Biochemistry', cat:'Medical', color:'#3ecf8e', free:false,
    desc:'Molecular mechanisms behind life — metabolism, genetics, and cell biology.',
    image:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/201_DNA_Replication.jpg/400px-201_DNA_Replication.jpg',
    staticImages:['https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Glycolysis_overview.svg/300px-Glycolysis_overview.svg.png'],
    topics:['Amino Acids & Proteins','Enzyme Kinetics','Carbohydrate Metabolism','Lipid Metabolism','Nucleotide Metabolism','DNA Replication & Repair','Gene Expression','Vitamins & Cofactors'] },
  { id:'patho', icon:'🔬', title:'Pathology', cat:'Medical', color:'#a78bfa', free:false,
    desc:'Disease mechanisms, cellular injury, inflammation, and systemic pathology.',
    image:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Acute_myocardial_infarction_with_coagulation_necrosis_%281%29.jpg/400px-Acute_myocardial_infarction_with_coagulation_necrosis_%281%29.jpg',
    staticImages:[],
    topics:['Cell Injury & Death','Inflammation','Neoplasia','Cardiovascular Pathology','Pulmonary Pathology','GI Pathology','Renal Pathology','Neuropathology'] },
  { id:'pharma', icon:'💊', title:'Pharmacology', cat:'Medical', color:'#f5a623', free:false,
    desc:'Drug mechanisms, pharmacokinetics, and clinical applications.',
    image:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Pharmacokinetics_parameters.png/400px-Pharmacokinetics_parameters.png',
    staticImages:['https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Blausen_0800_ReceptorTypes.png/300px-Blausen_0800_ReceptorTypes.png'],
    topics:['Pharmacokinetics','Autonomic Drugs','Cardiovascular Drugs','CNS Pharmacology','Antibiotics','Antifungals & Antivirals','Endocrine Drugs','Chemotherapy'] },
  { id:'micro', icon:'🦠', title:'Microbiology', cat:'Medical', color:'#3ecf8e', free:false,
    desc:'Bacteria, viruses, fungi, and parasites — identification and clinical relevance.',
    image:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Gram_stain_01.jpg/400px-Gram_stain_01.jpg',
    staticImages:[],
    topics:['Bacteriology Basics','Gram-Positive Bacteria','Gram-Negative Bacteria','Virology','Mycology','Parasitology','Immunology Basics','Clinical Microbiology'] },
  { id:'immuno', icon:'🛡️', title:'Immunology', cat:'Medical', color:'#4f8ef7', free:false,
    desc:'The immune system, host defense, autoimmunity, and hypersensitivity.',
    image:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/1201_Overview_of_Neuron.jpg/300px-1201_Overview_of_Neuron.jpg',
    staticImages:[],
    topics:['Innate Immunity','Adaptive Immunity','T & B Lymphocytes','MHC & Antigen Presentation','Hypersensitivity Reactions','Autoimmune Diseases','Immunodeficiencies','Vaccines'] },
  { id:'neuro', icon:'🧠', title:'Neuroscience', cat:'Medical', color:'#f76f6f', free:false,
    desc:'Brain, spinal cord, and peripheral nervous system in health and disease.',
    image:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/PurkinjeCell.jpg/400px-PurkinjeCell.jpg',
    staticImages:['https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Cerebrum_lobes.svg/300px-Cerebrum_lobes.svg.png'],
    topics:['Neural Signaling','Sensory Systems','Motor Systems','Autonomic Nervous System','Cerebral Cortex','Memory & Learning','Stroke & Neurological Disease','Psychiatry Basics'] },
  { id:'bio', icon:'🌿', title:'General Biology', cat:'Premed', color:'#3ecf8e', free:true,
    desc:'Foundational biology: cells, genetics, evolution — the MCAT backbone.',
    image:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Prokaryote_cell_diagram.svg/400px-Prokaryote_cell_diagram.svg.png',
    staticImages:['https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Mitosis_cells_sequence.svg/300px-Mitosis_cells_sequence.svg.png'],
    topics:['Cell Structure & Function','Mitosis & Meiosis','Genetics & Inheritance','Protein Synthesis','Enzymes & Metabolism','Evolution','Ecology','Biotechnology'] },
  { id:'chem', icon:'⚗️', title:'General Chemistry', cat:'Premed', color:'#4f8ef7', free:true,
    desc:'Atomic structure, bonding, equilibrium, and thermodynamics for the MCAT.',
    image:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Periodic_table_large.svg/400px-Periodic_table_large.svg.png',
    staticImages:['https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Covalent_bond_hydrogen.svg/300px-Covalent_bond_hydrogen.svg.png'],
    topics:['Atomic Structure','Chemical Bonding','Stoichiometry','Acids & Bases','Equilibrium','Thermodynamics','Electrochemistry','Nuclear Chemistry'] },
  { id:'ochem', icon:'🔗', title:'Organic Chemistry', cat:'Premed', color:'#f5a623', free:false,
    desc:'Functional groups, reaction mechanisms, stereochemistry, and spectroscopy.',
    image:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Benzene_structure.svg/400px-Benzene_structure.svg.png',
    staticImages:[],
    topics:['Functional Groups','Stereochemistry','Substitution & Elimination','Addition Reactions','Carbonyl Chemistry','Spectroscopy (NMR/IR)','Amino Acids','Carbohydrates & Lipids'] },
  { id:'physics', icon:'🔭', title:'Physics for Medicine', cat:'Premed', color:'#a78bfa', free:false,
    desc:'Mechanics, fluids, electricity, optics, and radiation — MCAT-relevant.',
    image:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Laminar_and_turbulent_flow.jpg/400px-Laminar_and_turbulent_flow.jpg',
    staticImages:[],
    topics:['Mechanics & Kinematics','Work, Energy & Power','Fluid Dynamics','Waves & Sound','Optics & Light','Electricity & Magnetism','Atomic & Nuclear Physics','Radiation & Imaging'] },
  { id:'psych', icon:'🧩', title:'Psychology & Sociology', cat:'Premed', color:'#f76f6f', free:false,
    desc:'Behavioral science for the MCAT — perception, cognition, social behavior.',
    image:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Maslow%27s_Hierarchy_of_Needs2.svg/400px-Maslow%27s_Hierarchy_of_Needs2.svg.png',
    staticImages:[],
    topics:['Perception & Sensation','Learning & Memory','Motivation & Emotion','Developmental Psychology','Social Behavior','Identity & Personality','Health Disparities','Research Methods'] },
  { id:'stats', icon:'📊', title:'Biostatistics & Epidemiology', cat:'Premed', color:'#3ecf8e', free:false,
    desc:'Research design, statistical tests, and population health.',
    image:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Simple_Normal_Distribution.svg/400px-Simple_Normal_Distribution.svg.png',
    staticImages:['https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Kaplan-Meier_Plot.png/300px-Kaplan-Meier_Plot.png'],
    topics:['Descriptive Statistics','Probability & Distributions','Hypothesis Testing','Confidence Intervals','Regression Analysis','Study Design','Bias & Confounding','Epidemiological Measures'] },
];

export const QUIZ_LIMITS = { free: 10, pro: 100, annual: 150 };
export const FLASH_LIMITS = { free: 15, pro: 100, annual: 150 };
